// Package entity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package entity

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Channel defines model for Channel.
type Channel struct {
	// YouTube によって割り振られる ID
	Id string `json:"id"`

	// YouTube で設定されているチャンネル名
	Name *string `json:"name,omitempty"`

	// YouTube で設定されているチャンネルのサムネイルの URL
	Thumbnail *string `json:"thumbnail,omitempty"`

	// チャンネルのURL
	Url *string `json:"url,omitempty"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ユーザーによって命名されたチャンネルリストの名前
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	// YouTube によって割り振られるチャンネル ID
	Id string `json:"id"`

	// YouTube で設定されているチャンネルの名前
	Name string `json:"name"`

	// YouTube で設定されているチャンネルのサムネイルの URL
	Thumbnail string `json:"thumbnail"`
}

// Video defines model for Video.
type Video struct {
	// YouTube によって割り振られる ID
	Id string `json:"id"`

	// 動画の公開日
	PublishedAt time.Time `json:"publishedAt"`

	// YouTube で設定されている動画のサムネイルの URL
	Thumbnail string `json:"thumbnail"`

	// YouTube で設定されている動画のタイトル
	Title string `json:"title"`

	// 動画の URL
	Url string `json:"url"`
}

// ChannelId defines model for ChannelId.
type ChannelId = string

// ChannelListId defines model for ChannelListId.
type ChannelListId = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PostChannelListsJSONBody defines parameters for PostChannelLists.
type PostChannelListsJSONBody = ChannelList

// PatchChannelListsIdJSONBody defines parameters for PatchChannelListsId.
type PatchChannelListsIdJSONBody = ChannelList

// PostChannelListsIdChannelsJSONBody defines parameters for PostChannelListsIdChannels.
type PostChannelListsIdChannelsJSONBody = []Channel

// GetUserLoginParams defines parameters for GetUserLogin.
type GetUserLoginParams struct {
	// OAuth2 から渡された承認コード
	Code string `form:"code" json:"code"`
}

// PostChannelListsJSONRequestBody defines body for PostChannelLists for application/json ContentType.
type PostChannelListsJSONRequestBody = PostChannelListsJSONBody

// PatchChannelListsIdJSONRequestBody defines body for PatchChannelListsId for application/json ContentType.
type PatchChannelListsIdJSONRequestBody = PatchChannelListsIdJSONBody

// PostChannelListsIdChannelsJSONRequestBody defines body for PostChannelListsIdChannels for application/json ContentType.
type PostChannelListsIdChannelsJSONRequestBody = PostChannelListsIdChannelsJSONBody
