// Package entities provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package entities

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Channel defines model for Channel.
type Channel struct {
	// YouTube によって割り振られる ID
	Id string `json:"id"`

	// YouTube で設定されているチャンネル名
	Name *string `json:"name,omitempty"`

	// YouTube で設定されているチャンネルのサムネイルの URL
	Thumbnail *string `json:"thumbnail,omitempty"`

	// チャンネルのURL
	Url *string `json:"url,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// List defines model for List.
type List struct {
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ユーザーによって命名されたチャンネルリストの名前
	Title string `json:"title"`
}

// User defines model for User.
type User struct {
	// YouTube によって割り振られるチャンネル ID
	Id string `json:"id"`

	// YouTube で設定されているチャンネルの名前
	Name string `json:"name"`

	// YouTube で設定されているチャンネルのサムネイルの URL
	Thumbnail string `json:"thumbnail"`
}

// Video defines model for Video.
type Video struct {
	// YouTube によって割り振られる ID
	Id string `json:"id"`

	// 動画の公開日
	PublishedAt time.Time `json:"publishedAt"`

	// YouTube で設定されている動画のサムネイルの URL
	Thumbnail string `json:"thumbnail"`

	// YouTube で設定されている動画のタイトル
	Title string `json:"title"`

	// 動画の URL
	Url string `json:"url"`
}

// ChannelId defines model for ChannelId.
type ChannelId = string

// ListId defines model for ListId.
type ListId = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PostListsJSONBody defines parameters for PostLists.
type PostListsJSONBody = List

// PatchListsIdJSONBody defines parameters for PatchListsId.
type PatchListsIdJSONBody = List

// PostListsIdChannelsJSONBody defines parameters for PostListsIdChannels.
type PostListsIdChannelsJSONBody = []Channel

// GetUsersLoginParams defines parameters for GetUsersLogin.
type GetUsersLoginParams struct {
	// OAuth2 から渡された承認コード
	Code string `form:"code" json:"code"`
}

// PostListsJSONRequestBody defines body for PostLists for application/json ContentType.
type PostListsJSONRequestBody = PostListsJSONBody

// PatchListsIdJSONRequestBody defines body for PatchListsId for application/json ContentType.
type PatchListsIdJSONRequestBody = PatchListsIdJSONBody

// PostListsIdChannelsJSONRequestBody defines body for PostListsIdChannels for application/json ContentType.
type PostListsIdChannelsJSONRequestBody = PostListsIdChannelsJSONBody
